Build Started 17_01_2022_16:39:08
2022-01-17 18:39:58.478 7 INFO cinder.rpc [req-93b12f8b-cea8-48a2-bf8d-476ddc8eb848 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume [req-93b12f8b-cea8-48a2-bf8d-476ddc8eb848 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:39:58.479 7 ERROR cinder.cmd.volume 
2022-01-17 18:39:58.482 7 ERROR cinder.cmd.volume [req-93b12f8b-cea8-48a2-bf8d-476ddc8eb848 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:05.361 7 INFO cinder.rpc [req-7adf0cef-2356-4c66-9f24-2a9b6f398458 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume [req-7adf0cef-2356-4c66-9f24-2a9b6f398458 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:05.362 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:05.365 7 ERROR cinder.cmd.volume [req-7adf0cef-2356-4c66-9f24-2a9b6f398458 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:09.534 7 INFO cinder.rpc [req-57f673cc-b269-4b0a-b72f-8653563b6442 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume [req-57f673cc-b269-4b0a-b72f-8653563b6442 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:09.535 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:09.538 7 ERROR cinder.cmd.volume [req-57f673cc-b269-4b0a-b72f-8653563b6442 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:13.918 7 INFO cinder.rpc [req-a7dccc23-a353-4762-a499-44a68140488b - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume [req-a7dccc23-a353-4762-a499-44a68140488b - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:13.919 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:13.922 7 ERROR cinder.cmd.volume [req-a7dccc23-a353-4762-a499-44a68140488b - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:18.691 7 INFO cinder.rpc [req-3121538a-1fa8-4dc0-bb8f-deb9cd24f29d - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume [req-3121538a-1fa8-4dc0-bb8f-deb9cd24f29d - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:18.692 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:18.695 7 ERROR cinder.cmd.volume [req-3121538a-1fa8-4dc0-bb8f-deb9cd24f29d - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:24.271 7 INFO cinder.rpc [req-081d17bc-b428-4e5c-bff8-c7b8ff0b0970 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume [req-081d17bc-b428-4e5c-bff8-c7b8ff0b0970 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:24.271 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:24.274 7 ERROR cinder.cmd.volume [req-081d17bc-b428-4e5c-bff8-c7b8ff0b0970 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:31.439 7 INFO cinder.rpc [req-40c755a8-83a5-42a9-a627-35819acd4186 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume [req-40c755a8-83a5-42a9-a627-35819acd4186 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:31.440 7 ERROR cinder.cmd.volume 
2022-01-17 18:40:31.443 7 ERROR cinder.cmd.volume [req-40c755a8-83a5-42a9-a627-35819acd4186 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:41.802 8 INFO cinder.rpc [req-50e8d431-cf4f-4422-84ce-0c652c9f1392 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume [req-50e8d431-cf4f-4422-84ce-0c652c9f1392 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:41.803 8 ERROR cinder.cmd.volume 
2022-01-17 18:40:41.806 8 ERROR cinder.cmd.volume [req-50e8d431-cf4f-4422-84ce-0c652c9f1392 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:40:58.625 9 INFO cinder.rpc [req-ffbf2761-8af7-4baa-b7a7-98c9de52ce6a - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume [req-ffbf2761-8af7-4baa-b7a7-98c9de52ce6a - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:40:58.625 9 ERROR cinder.cmd.volume 
2022-01-17 18:40:58.628 9 ERROR cinder.cmd.volume [req-ffbf2761-8af7-4baa-b7a7-98c9de52ce6a - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:41:28.192 7 INFO cinder.rpc [req-ebab3794-4318-4aad-901c-4c06c0ff9a6e - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume [req-ebab3794-4318-4aad-901c-4c06c0ff9a6e - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:41:28.193 7 ERROR cinder.cmd.volume 
2022-01-17 18:41:28.196 7 ERROR cinder.cmd.volume [req-ebab3794-4318-4aad-901c-4c06c0ff9a6e - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:42:25.543 7 INFO cinder.rpc [req-02983a4e-9c77-43ce-ae6b-ffd3098dd215 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume [req-02983a4e-9c77-43ce-ae6b-ffd3098dd215 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:42:25.544 7 ERROR cinder.cmd.volume 
2022-01-17 18:42:25.547 7 ERROR cinder.cmd.volume [req-02983a4e-9c77-43ce-ae6b-ffd3098dd215 - - - - -] No volume service(s) started successfully, terminating.
2022-01-17 18:43:29.343 7 INFO cinder.rpc [req-23c88519-82b4-4157-9092-e95a3b6de2f1 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume [req-23c88519-82b4-4157-9092-e95a3b6de2f1 - - - - -] Volume service rack02-server77@LIGHTOStbibzy failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume Traceback (most recent call last):
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/cmd/volume.py", line 99, in _launch_service
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     server = service.Service.create(host=host,
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 394, in create
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/service.py", line 152, in __init__
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 220, in __init__
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 185, in __init__
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/rpc.py", line 212, in __init__
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/objects/base.py", line 552, in __init__
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
2022-01-17 18:43:29.344 7 ERROR cinder.cmd.volume 
2022-01-17 18:43:29.347 7 ERROR cinder.cmd.volume [req-23c88519-82b4-4157-9092-e95a3b6de2f1 - - - - -] No volume service(s) started successfully, terminating.
