Build Started 05_08_2022_07_40_25
2022-08-05 10:40:35.780 7 INFO oslo_service.service [req-dc2fcb81-cfbf-4e17-a7c0-e3183a7c964c - - - - -] Caught SIGTERM, stopping children
2022-08-05 10:40:35.791 7 INFO oslo_service.service [req-dc2fcb81-cfbf-4e17-a7c0-e3183a7c964c - - - - -] Waiting on 1 children to exit
2022-08-05 10:40:36.683 24 WARNING amqp [req-dc2fcb81-cfbf-4e17-a7c0-e3183a7c964c - - - - -] Received method (60, 30) during closing channel 1. This method will be ignored
2022-08-05 10:40:36.704 24 WARNING amqp [req-dc2fcb81-cfbf-4e17-a7c0-e3183a7c964c - - - - -] Received method (60, 30) during closing channel 1. This method will be ignored
2022-08-05 10:40:36.716 7 INFO oslo_service.service [req-dc2fcb81-cfbf-4e17-a7c0-e3183a7c964c - - - - -] Child 24 exited with status 0
2022-08-05 10:40:42.043 6 INFO cinder.rpc [req-a1260b56-562d-4570-a068-e41589bad933 - - - - -] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
2022-08-05 10:40:42.048 6 INFO cinder.rpc [req-a1260b56-562d-4570-a068-e41589bad933 - - - - -] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
2022-08-05 10:40:42.212 6 INFO cinder.volume.manager [req-a1260b56-562d-4570-a068-e41589bad933 - - - - -] Determined volume DB was not empty at startup.
2022-08-05 10:40:42.238 6 INFO cinder.volume.manager [req-a1260b56-562d-4570-a068-e41589bad933 - - - - -] Image-volume cache disabled for host rack03-server59@LIGHTOSsetykm.
2022-08-05 10:40:42.255 6 INFO oslo_service.service [req-a1260b56-562d-4570-a068-e41589bad933 - - - - -] Starting 1 workers
2022-08-05 10:40:42.266 23 INFO cinder.service [-] Starting cinder-volume node (version 20.0.0)
2022-08-05 10:40:42.287 23 INFO cinder.volume.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Starting volume driver LightOSVolumeDriver (2.3.12)
2022-08-05 10:40:42.288 23 INFO cinder.volume.drivers.lightos [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Invoking get_cluster_info using GET url: /api/v2/clusterinfo             request.body: {} ssl_verify: False
2022-08-05 10:40:42.374 23 INFO cinder.volume.drivers.lightos [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Connected to LightOS cluster 20262816-0d9a-4ea3-b7f6-8afed5735f34 subsysnqn nqn.2016-01.com.lightbitslabs:uuid:f37ef4ef-5bfc-40f0-90cf-ff2f68c58c0f
2022-08-05 10:40:42.375 23 INFO cinder.volume.drivers.lightos [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Invoking get_nodes using GET url: /api/v2/nodes             request.body: {} ssl_verify: False
2022-08-05 10:40:42.532 23 INFO cinder.keymgr.migration [req-4904650f-7bff-4018-9bb7-d2fe22f3eddd - - - - -] Not migrating encryption keys because the ConfKeyManager's fixed_key is not in use.
2022-08-05 10:40:42.546 23 INFO cinder.volume.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Driver initialization completed successfully.
2022-08-05 10:40:42.547 23 INFO cinder.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Initiating service 4 cleanup
2022-08-05 10:40:42.557 23 INFO cinder.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Service 4 cleanup completed.
2022-08-05 10:40:42.606 23 INFO cinder.volume.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Initializing RPC dependent components of volume driver LightOSVolumeDriver (2.3.12)
2022-08-05 10:40:42.617 23 INFO cinder.volume.manager [req-91c03c22-c017-4ad6-aec4-6930e3bfc313 - - - - -] Driver post RPC initialization completed successfully.
2022-08-05 10:42:12.189 23 INFO cinder.volume.drivers.lightos [req-dfffa582-04db-4ce9-bb90-164827f579f8 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking get_snapshot_by_name using GET url: /api/v2/projects/default/snapshots/?Name=snapshot-921e2d86-a91b-49e4-9523-2290d9a06d00             request.body: {} ssl_verify: False
2022-08-05 10:42:12.211 23 WARNING cinder.volume.drivers.lightos [req-dfffa582-04db-4ce9-bb90-164827f579f8 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Unable to find lightos snapshot snapshot-921e2d86-a91b-49e4-9523-2290d9a06d00 project default for deletion
2022-08-05 10:42:12.328 23 WARNING cinder.quota [req-dfffa582-04db-4ce9-bb90-164827f579f8 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deprecated: Default quota for resource: gigabytes___DEFAULT__ is set by the default quota flag: quota_gigabytes___DEFAULT__, it is now deprecated. Please use the default quota class for default quota.
2022-08-05 10:42:12.329 23 WARNING cinder.quota [req-dfffa582-04db-4ce9-bb90-164827f579f8 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deprecated: Default quota for resource: snapshots___DEFAULT__ is set by the default quota flag: quota_snapshots___DEFAULT__, it is now deprecated. Please use the default quota class for default quota.
2022-08-05 10:42:12.390 23 INFO cinder.volume.manager [req-dfffa582-04db-4ce9-bb90-164827f579f8 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Delete snapshot completed successfully.
2022-08-05 10:42:26.015 23 INFO cinder.volume.drivers.lightos [req-2708a4a4-4246-4303-9594-e167d94d98d7 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking get_volume_by_name using GET url: /api/v2/projects/default/volumes/?name=vol_c21c0ded-90ed-4421-8095-8f74cd0a31ef             request.body: {} ssl_verify: False
2022-08-05 10:42:26.030 23 ERROR cinder.volume.drivers.lightos [req-2708a4a4-4246-4303-9594-e167d94d98d7 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Failed to get LightOS volume vol_c21c0ded-90ed-4421-8095-8f74cd0a31ef project default status:                 404 data: {'error': 'failed to find volume with name vol_c21c0ded-90ed-4421-8095-8f74cd0a31ef', 'code': 5, 'message': 'failed to find volume with name vol_c21c0ded-90ed-4421-8095-8f74cd0a31ef', 'details': []}
2022-08-05 10:42:26.099 23 WARNING cinder.quota [req-2708a4a4-4246-4303-9594-e167d94d98d7 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deprecated: Default quota for resource: volumes___DEFAULT__ is set by the default quota flag: quota_volumes___DEFAULT__, it is now deprecated. Please use the default quota class for default quota.
2022-08-05 10:42:26.146 23 INFO cinder.volume.drivers.lightos [req-921da5d5-e9b2-45ef-84f7-a75aed3ecead d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking get_volume_by_name using GET url: /api/v2/projects/default/volumes/?name=vol_5a52bb11-ace1-4083-a180-2c627b6f3146             request.body: {} ssl_verify: False
2022-08-05 10:42:26.160 23 INFO cinder.volume.drivers.lightos [req-921da5d5-e9b2-45ef-84f7-a75aed3ecead d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking delete_volume using DELETE url: /api/v2/projects/default/volumes/59b19149-7591-4b3d-812f-c01ec875ef07?             request.body:  ssl_verify: False
2022-08-05 10:42:26.177 23 INFO cinder.volume.manager [req-2708a4a4-4246-4303-9594-e167d94d98d7 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deleted volume successfully.
2022-08-05 10:42:26.182 23 INFO cinder.volume.drivers.lightos [req-921da5d5-e9b2-45ef-84f7-a75aed3ecead d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking get_volume using GET url: /api/v2/projects/default/volumes/59b19149-7591-4b3d-812f-c01ec875ef07             request.body: {} ssl_verify: False
2022-08-05 10:42:26.299 23 INFO cinder.volume.drivers.lightos [req-2645a99c-51ac-4a3e-a06e-a8d0648cbc42 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Invoking get_volume_by_name using GET url: /api/v2/projects/default/volumes/?name=vol_2455f40a-0719-45a2-baeb-25da76ae1081             request.body: {} ssl_verify: False
2022-08-05 10:42:26.314 23 ERROR cinder.volume.drivers.lightos [req-2645a99c-51ac-4a3e-a06e-a8d0648cbc42 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Failed to get LightOS volume vol_2455f40a-0719-45a2-baeb-25da76ae1081 project default status:                 404 data: {'error': 'failed to find volume with name vol_2455f40a-0719-45a2-baeb-25da76ae1081', 'code': 5, 'message': 'failed to find volume with name vol_2455f40a-0719-45a2-baeb-25da76ae1081', 'details': []}
2022-08-05 10:42:26.338 23 INFO cinder.volume.manager [req-921da5d5-e9b2-45ef-84f7-a75aed3ecead d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deleted volume successfully.
2022-08-05 10:42:26.433 23 INFO cinder.volume.manager [req-2645a99c-51ac-4a3e-a06e-a8d0648cbc42 d1d157c049d4452ea5b849b7ac9ac3a0 82731ad45ae044fbb76d07586f6f60f2 - - -] Deleted volume successfully.
2022-08-05 10:58:11.588 23 ERROR oslo.messaging._drivers.impl_rabbit [req-3cfa133c-03bd-4e86-b810-c030da7699ef - - - - -] Failed to publish message to topic 'cinder-scheduler_fanout': Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/': amqp.exceptions.NotFound: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/'
2022-08-05 10:58:11.590 23 ERROR oslo.messaging._drivers.impl_rabbit [req-3cfa133c-03bd-4e86-b810-c030da7699ef - - - - -] Unable to connect to AMQP server on [LB_IP_ADDRESS]:5672 after inf tries: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/': amqp.exceptions.NotFound: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/'
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task [req-3cfa133c-03bd-4e86-b810-c030da7699ef - - - - -] Error during VolumeManager.publish_service_capabilities: oslo_messaging.exceptions.MessageDeliveryFailure: Unable to connect to AMQP server on [LB_IP_ADDRESS]:5672 after inf tries: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/'
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task Traceback (most recent call last):
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 868, in ensure
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     ret, channel = autoretry_method()
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/kombu/connection.py", line 524, in _ensured
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return fun(*args, **kwargs)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/kombu/connection.py", line 600, in __call__
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return fun(*args, channel=channels[0], **kwargs), channels[0]
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 857, in execute_method
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     method()
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1281, in _publish
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self._producer.publish(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return _publish(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/kombu/messaging.py", line 199, in _publish
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return channel.basic_publish(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/channel.py", line 1808, in basic_publish_confirm
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self.wait([spec.Basic.Ack, spec.Basic.Nack],
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/abstract_channel.py", line 86, in wait
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self.connection.drain_events(timeout=timeout)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/connection.py", line 522, in drain_events
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     while not self.blocking_read(timeout):
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/connection.py", line 528, in blocking_read
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return self.on_inbound_frame(frame)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/method_framing.py", line 53, in on_frame
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     callback(channel, method_sig, buf, None)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/connection.py", line 534, in on_inbound_method
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return self.channels[channel_id].dispatch_method(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     listener(*args)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/amqp/channel.py", line 281, in _on_close
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     raise error_for_code(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task amqp.exceptions.NotFound: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/'
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task 
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task During handling of the above exception, another exception occurred:
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task 
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task Traceback (most recent call last):
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_service/periodic_task.py", line 216, in run_periodic_tasks
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     task(self, context)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/volume/manager.py", line 2875, in publish_service_capabilities
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self._publish_service_capabilities(context)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/manager.py", line 203, in _publish_service_capabilities
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self.scheduler_rpcapi.update_service_capabilities(
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/cinder/scheduler/rpcapi.py", line 222, in update_service_capabilities
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     cctxt.cast(ctxt, 'update_service_capabilities', **msg_args)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/client.py", line 155, in cast
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self.transport._send(self.target, msg_ctxt, msg,
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/transport.py", line 123, in _send
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return self._driver.send(target, ctxt, message,
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 689, in send
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     return self._send(target, ctxt, message, wait_for_reply, timeout,
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 664, in _send
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     conn.fanout_send(target.topic, msg, retry=retry)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1391, in fanout_send
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self._ensure_publishing(self._publish, exchange, msg, retry=retry)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1245, in _ensure_publishing
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     self.ensure(method, retry=retry, error_callback=_error_callback)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 890, in ensure
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task     raise exceptions.MessageDeliveryFailure(msg)
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task oslo_messaging.exceptions.MessageDeliveryFailure: Unable to connect to AMQP server on [LB_IP_ADDRESS]:5672 after inf tries: Basic.publish: (404) NOT_FOUND - no exchange 'cinder-scheduler_fanout' in vhost '/'
2022-08-05 10:58:11.591 23 ERROR oslo_service.periodic_task 
